### ISSUE TITLE
Inactive slack invite link

### ISSUE THREAD

**Issue by computermode** [Helpful-Engineers/resources#57]
Hi there! My friends and I would like to join, but it seems the slack link is no longer valid. How can we get an invite to the group?

Thanks!

**Comment by jdnarvaez** [comment]
https://join.slack.com/t/helpfulengineering/shared_invite/zt-cuftcntg-BDc~3oBJ7izijjdmZ6CxZg

**Comment by computermode** [comment]
Thank you!
